spring:
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  application:
    name: consultant-business-api
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@${DB_CLUSTER_URL}/${DB_NAME}?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null

cloudinary:
  enabled: ${CLOUDINARY_ENABLED:true}
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
  folder: ${CLOUDINARY_FOLDER:consulting-cherif}

app:
  mail:
    from: ${MAIL_FROM:no-reply@consultant-business-api}
  security:
    otp:
      expiration-minutes: 10
    jwt:
      access-token-expiration: 86400000 # 24 hours for local testing
      refresh-token-expiration: 604800000 # 7 days
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail

